name: Run Blender with Python Script

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Blender (replace with your preferred method)
      - name: Install Blender
        run: |
          wget https://www.blender.org/download/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz/
          tar xvf blender-4.2.0-linux-x64.tar.xz
          export PATH="$PATH:/path/to/blender/blender"

     

      - name: Run Python Script
        run: python btest.py

      - name: Run Blender
        run: blender -b test_drone.blend -P test_drone.py