name: Run Blender with Python Script

on:
  push:
    branches: [main, trial]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # - name: Install Python dependencies
      #   run: pip install -r requirements.txt 

      # Install Blender (replace with your preferred method)
      - name: Install Blender
        run: |
          pwd
          wget -c -O blender-4.2.0-linux-x64 https://ftp.halifax.rwth-aachen.de/blender/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz
          tar -xvf blender-4.2.0-linux-x64
          sudo apt-get update
          sudo apt-get install libegl1-mesa
          cd blender-4.2.0-linux-x64
          echo "Something"
          pwd
          ls

      - name: Run Python Script
        run: python btest.py

      # - name: Run Blender
      #   run: blender -b test_drone.blend -P test_drone.py