name: Install Blender Addon

on: [push]

jobs:
  install-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Blender (if not included in the repository)
        run: |
          wget https://download.blender.org/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz
          tar -xf blender-4.2.0-linux-x64.tar.xz
          ls -la blender-4.2.0-linux-x64
      
      - name: Install Python dependencies (if needed)
        run: |
          cd /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/4.2/python/bin
          pwd
          python -m pip install --target "/home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/4.2/python/lib/site-packages" scipy
          echo "BUNYT"
          pwd

      - name: Create install_addon.py script
        run: |
          echo "
          import bpy
          import os
          import time

          time.sleep(5)  # Add delay to ensure Blender initializes
          
          addon_path = '/home/runner/work/github-trial/github-trial/animation_tool.zip'
          print(f'Installing addon from {addon_path}')
          
          if os.path.exists(addon_path):
              bpy.ops.wm.addon_install(filepath=addon_path)
              bpy.ops.wm.addon_enable(module='animation_tool')
              bpy.ops.wm.save_userpref()
              print('Addon installed successfully')
          else:
              print(f'Addon path {addon_path} does not exist!')
          " > install_addon.py

      - name: Run install_addon.py in Blender
        run: |
          cd /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64
          ./blender --background --python ../install_addon.py
