name: Install Blender Addon

on: [push]

jobs:
  install-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Download Blender (if not included in the repository)
        run: |
          wget https://download.blender.org/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz
          tar -xf blender-4.2.0-linux-x64.tar.xz
      
      - name: Install Python dependencies (if needed)
        run: |
          ccd /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64
          ls
          pwd
          cd /home/runner/work/github-trial/blender-4.2.0-linux-x64/blender-4.2.0-linux-x64/4.2/python/bin
          ls
          pwd
          /blender-4.2.0-linux-x64/4.2/python/bin/python3.11 -m pip install --target "/home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/4.2/python/lib/site-packages" scipy
          pwd
      
      

      - name: Create install_addon.py script
        run: |
          echo "
          import bpy
          import os
          import time

          time.sleep(15)  # Add delay to ensure Blender initializes
          
          addon_path = '/home/runner/work/github-trial/github-trial/animation_tool.zip'
       

          bpy.ops.preferences.addon_install(filepath=addon_path)
          bpy.ops.preferences.addon_enable(module="animation_tool.zip")
          " > install_addon.py

      - name: Run install_addon.py in Blender
        run: |
          cd /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64
          ./blender --background --python ../install_addon.py

      - name: Test Drone
        run: |
          cd /home/runner/work/github-trial/github-trial
          python btest.py
