name: Install Blender Addon

on: [push]

jobs:
  install-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Blender (if not included in the repository)
        run: |
          wget https://download.blender.org/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz
          tar -xf blender-4.2.0-linux-x64.tar.xz
          ls -la blender-4.2.0-linux-x64
          pwd

      - name: Install Python dependencies (if needed)
        run: |
          pwd
          python -m pip install --target "/home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/4.2/python/lib/site-packages" scipy

      - name: Install Blender Addon from .zip
        run: |
          pwd
          cd /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/4.2/python/bin
          ./blender --background --python-expr "
          import bpy
          import os
          addon_path = os.path.join(os.getcwd(), "/home/runner/work/github-trial/github-trial/animation_tool.zip")
          bpy.ops.wm.addon_install(filepath=addon_path)
          bpy.ops.wm.addon_enable(module='Metadata Beta 1.5.2')
          bpy.ops.wm.save_userpref()
          print('Addon installed successfully')"
