name: Blender Tests

on: [push]

jobs:
  install-addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Download Blender
        run: |
          wget https://download.blender.org/release/Blender4.2/blender-4.2.0-linux-x64.tar.xz
          tar -xf blender-4.2.0-linux-x64.tar.xz
      
      - name: Install Python Scipy
        run: |
          pwd

          #Update pip
          /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/4.2/python/bin/python3.11 -m pip install --upgrade pip

          blender-4.2.0-linux-x64/4.2/python/bin/python3.11 -m pip install --target "blender-4.2.0-linux-x64/4.2/python/lib/site-packages" scipy
          
          echo "SPACE"
          cd blender-4.2.0-linux-x64/4.2/python/lib/site-packages
          ls
        
      - name: Download Animation Toop .zip file
        run: |
          pwd

          /home/runner/work/github-trial/github-trial/blender-4.2.0-linux-x64/blender  --background --python-expr "
          import bpy

          path_to_zip='/home/runner/work/github-trial/github-trial/'

          bpy.ops.preferences.addon_install(filepath=path_to_zip)
          bpy.ops.preferences.addon_enable(module="animation_tool")"
          
          
